export const shortDestinations = {
    "1": {
      "id": "1",
      "from": "3",
      "to": "2",
      "fromCity": "Athina",
      "toCity": "Angora",
      "value": "5",
    },
    "2": {
      "id": "2",
      "from": "10",
      "to": "40",
      "fromCity": "Budapest",
      "toCity": "Sofia",
      "value": "5",
    },
    "3": {
      "id": "3",
      "from": "18",
      "to": "20",
      "fromCity": "Frankfurt",
      "toCity": "Kobenhavn",
      "value": "5",
    },
    "4": {
      "id": "4",
      "from": "34",
      "to": "16",
      "fromCity": "Rostov",
      "toCity": "Erzurum",
      "value": "5",
    },
    "5": {
      "id": "5",
      "from": "40",
      "to": "38",
      "fromCity": "Sofia",
      "toCity": "Smyrna",
      "value": "5",
    },
    "6": {
      "id": "6",
      "from": "21",
      "to": "31",
      "fromCity": "Kyiv",
      "toCity": "Petrograd",
      "value": "6",
    },
    "7": {
      "id": "7",
      "from": "47",
      "to": "7",
      "fromCity": "Zurich",
      "toCity": "Brindisi",
      "value": "6",
    },
    "8": {
      "id": "8",
      "from": "47",
      "to": "10",
      "fromCity": "Zurich",
      "toCity": "Budapest",
      "value": "6",
    },
    "9": {
      "id": "9",
      "from": "43",
      "to": "37",
      "fromCity": "Warszawa",
      "toCity": "Smolensk",
      "value": "6",
    },
    "10": {
      "id": "10",
      "from": "46",
      "to": "7",
      "fromCity": "Zagrab",
      "toCity": "Brindisi",
      "value": "6",
    },
    "11": {
      "id": "11",
      "from": "30",
      "to": "46",
      "fromCity": "Paris",
      "toCity": "Zagrab",
      "value": "7",
    },
    "12": {
      "id": "12",
      "from": "6",
      "to": "25",
      "fromCity": "Brest",
      "toCity": "Marseille",
      "value": "7",
    },
    "13": {
      "id": "13",
      "from": "23",
      "to": "5",
      "fromCity": "London",
      "toCity": "Berlin",
      "value": "7",
    },
    "14": {
      "id": "14",
      "from": "15",
      "to": "30",
      "fromCity": "Edinburgh",
      "toCity": "Paris",
      "value": "7",
    },
    "15": {
      "id": "15",
      "from": "1",
      "to": "29",
      "fromCity": "Amsterdam",
      "toCity": "Pamplona",
      "value": "7",
    },
    "16": {
      "id": "16",
      "from": "33",
      "to": "38",
      "fromCity": "Roma",
      "toCity": "Smyrna",
      "value": "8",
    },
    "17": {
      "id": "17",
      "from": "28",
      "to": "12",
      "fromCity": "Palermo",
      "toCity": "Constantinople",
      "value": "8",
    },
    "18": {
      "id": "18",
      "from": "35",
      "to": "36",
      "fromCity": "Sarajevo",
      "toCity": "Sevastopol",
      "value": "8",
    },
    "19": {
      "id": "19",
      "from": "24",
      "to": "14",
      "fromCity": "Madrid",
      "toCity": "Dieppe",
      "value": "8",
    },
    "20": {
      "id": "20",
      "from": "4",
      "to": "8",
      "fromCity": "Barcelona",
      "toCity": "Bruxelles",
      "value": "8",
    },
    "21": {
      "id": "21",
      "from": "30",
      "to": "44",
      "fromCity": "Paris",
      "toCity": "Wien",
      "value": "8",
    },
    "22": {
      "id": "22",
      "from": "4",
      "to": "27",
      "fromCity": "Barcelona",
      "toCity": "Munchen",
      "value": "8",
    },
    "23": {
      "id": "23",
      "from": "6",
      "to": "42",
      "fromCity": "Brest",
      "toCity": "Venezia",
      "value": "8",
    },
    "24": {
      "id": "24",
      "from": "37",
      "to": "34",
      "fromCity": "Smolensk",
      "toCity": "Rostov",
      "value": "8",
    },
    "25": {
      "id": "25",
      "from": "25",
      "to": "17",
      "fromCity": "Marseille",
      "toCity": "Essen",
      "value": "8",
    },
    "26": {
      "id": "26",
      "from": "21",
      "to": "39",
      "fromCity": "Kyiv",
      "toCity": "Sochi",
      "value": "8",
    },
    "27": {
      "id": "27",
      "from": "24",
      "to": "47",
      "fromCity": "Madrid",
      "toCity": "Zurich",
      "value": "8",
    },
    "28": {
      "id": "28",
      "from": "5",
      "to": "9",
      "fromCity": "Berlin",
      "toCity": "Bucuresti",
      "value": "8",
    },
    "29": {
      "id": "29",
      "from": "8",
      "to": "13",
      "fromCity": "Bruxelles",
      "toCity": "Danzig",
      "value": "9",
    },
    "30": {
      "id": "30",
      "from": "5",
      "to": "33",
      "fromCity": "Berlin",
      "toCity": "Roma",
      "value": "9",
    },
    "31": {
      "id": "31",
      "from": "2",
      "to": "19",
      "fromCity": "Angora",
      "toCity": "Kharkov",
      "value": "10",
    },
    "32": {
      "id": "32",
      "from": "32",
      "to": "9",
      "fromCity": "Riga",
      "toCity": "Bucuresti",
      "value": "10",
    },
    "33": {
      "id": "33",
      "from": "17",
      "to": "21",
      "fromCity": "Essen",
      "toCity": "Kyiv",
      "value": "10",
    },
    "34": {
      "id": "34",
      "from": "42",
      "to": "12",
      "fromCity": "Venezia",
      "toCity": "Constantinople",
      "value": "10",
    },
    "35": {
      "id": "35",
      "from": "23",
      "to": "44",
      "fromCity": "London",
      "toCity": "Wien",
      "value": "10",
    },
    "36": {
      "id": "36",
      "from": "3",
      "to": "45",
      "fromCity": "Athina",
      "toCity": "Wilno",
      "value": "11",
    },
    "37": {
      "id": "37",
      "from": "41",
      "to": "44",
      "fromCity": "Stockholm",
      "toCity": "Wien",
      "value": "11",
    },
    "38": {
      "id": "38",
      "from": "5",
      "to": "26",
      "fromCity": "Berlin",
      "toCity": "Moskva",
      "value": "12",
    },
    "39": {
      "id": "39",
      "from": "1",
      "to": "45",
      "fromCity": "Amsterdam",
      "toCity": "Wilno",
      "value": "12",
    },
    "40": {
      "id": "40",
      "from": "18",
      "to": "37",
      "fromCity": "Frankfurt",
      "toCity": "Smolensk",
      "value": "13",
    }
}

export const longDestinations = {
    "41": {
      "id": "41",
      "from": "22",
      "to": "13",
      "fromCity": "Lisboa",
      "toCity": "Danzig",
      "value": "20",
    },
    "42": {
      "id": "42",
      "from": "6",
      "to": "31",
      "fromCity": "Brest",
      "toCity": "Petrograd",
      "value": "20",
    },
    "43": {
      "id": "43",
      "from": "28",
      "to": "26",
      "fromCity": "Palermo",
      "toCity": "Moskva",
      "value": "20",
    },
    "44": {
      "id": "44",
      "from": "20",
      "to": "16",
      "fromCity": "Kobenhavn",
      "toCity": "Erzurum",
      "value": "21",
    },
    "45": {
      "id": "45",
      "from": "15",
      "to": "3",
      "fromCity": "Edinburgh",
      "toCity": "Athina",
      "value": "21",
    },
    "46": {
      "id": "46",
      "from": "11",
      "to": "41",
      "fromCity": "Cadiz",
      "toCity": "Stockholm",
      "value": "21",
    }
}
